import os
import json
import datetime
from anthropic import AsyncAnthropic
from graph.state import SAATHIState, ConversationStage
from twin.anonymizer import anonymize_context

# Initialize Anthropic Async client
client = AsyncAnthropic(api_key=os.getenv("ANTHROPIC_API_KEY", "mock-key"))

# System prompt for Life Event Predictor
LIFE_EVENT_SYSTEM = """
You are a financial signal analyst for SBI bank.
Given an anonymized banking transaction event, classify it into a life-event tag.

Available tags:
- new_professional: First 1-3 salary credits, no existing investments
- salary_growth: Salary increased > 20% vs last 6 months
- emi_cleared: Recurring loan EMI stopped (debt-free moment)
- school_fee_cycle: Education payment in Feb-March
- travel_gap: High travel spend with no travel insurance
- investment_ready: Balance > 3x monthly income, no investments

Respond ONLY with valid JSON (no markdown formatting, no other text):
{
  "tag": "new_professional" | "salary_growth" | "emi_cleared" | "school_fee_cycle" | "travel_gap" | "investment_ready" | null,
  "confidence": 0.0-1.0,
  "rationale": "<one sentence explanation>"
}
"""

async def predict_life_event(state: SAATHIState) -> SAATHIState:
    """
    Life-Event Predictor Agent.
    Sanitizes PII and uses Claude to classify transaction context into a life-event tag.
    """
    # 1. Anonymize context
    context = anonymize_context({
        "trigger_type": state["trigger_type"],
        "trigger_amount": state["trigger_amount"],
        "account_balance": state["account_balance"],
        "income_tier": state["income_tier"],
        "risk_score": state["risk_score"],
    })
    
    # 2. Invoke Anthropic API or fallback to heuristics if key is mock
    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    result = None
    
    if api_key and not api_key.startswith("your-") and not api_key == "mock-key":
        try:
            response = await client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=200,
                system=LIFE_EVENT_SYSTEM,
                messages=[{"role": "user", "content": f"Transaction context: {json.dumps(context)}"}],
                temperature=0.0
            )
            raw_text = response.content[0].text.strip()
            # Handle markdown codeblock enclosures if generated by LLM
            if raw_text.startswith("```"):
                lines = raw_text.split("\n")
                if lines[0].strip().startswith("```json") or lines[0].strip().startswith("```"):
                    raw_text = "\n".join(lines[1:-1])
            result = json.loads(raw_text)
        except Exception as e:
            print(f"[Life-Event Predictor] LLM call failed ({e}). Using rule-based fallback.")
            
    if result is None:
        # Demo-specific rule-based backup mapping
        trigger = state["trigger_type"]
        amount = state["trigger_amount"]
        
        if trigger == "salary_credit":
            result = {
                "tag": "new_professional",
                "confidence": 0.95,
                "rationale": f"Salary credit of ₹{amount:,.0f} matches the first professional credit event."
            }
        elif trigger == "emi_cleared":
            result = {
                "tag": "emi_cleared",
                "confidence": 0.92,
                "rationale": "Recurring monthly EMI stopped, releasing investable balance."
            }
        elif trigger == "high_travel_spend":
            result = {
                "tag": "travel_gap",
                "confidence": 0.88,
                "rationale": "Large travel expenditure detected with no travel insurance holdings."
            }
        else:
            result = {
                "tag": None,
                "confidence": 0.0,
                "rationale": "Transaction pattern did not trigger any target life event."
            }
            
    # 3. Post-process confidence thresholds (If confidence < 0.6, tag: null)
    if result.get("confidence", 0.0) < 0.6:
        result["tag"] = None
        
    state["life_event_tag"] = result.get("tag")
    state["stage"] = ConversationStage.LIFE_EVENT_IDENTIFIED
    
    # 4. Append to audit trail
    state["audit_trail"].append({
        "agent": "life_event_predictor",
        "output": result,
        "timestamp": datetime.datetime.utcnow().isoformat()
    })
    
    return state
